configured_endpoints: 123
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/unity-ai-solutions%2Fbandlab-sdk-e9fb5f50d7611b987057db88caeff8183f5d35f2cce83c930706cedb1efb90bb.yml
openapi_spec_hash: 3fcf9af7f10bbb3a0d447cdaeb776679
config_hash: 859efd139fe6e60b06140aad6560c5da
